### ISSUE TITLE
Output tables: Name of column "numberOfVaccinations"

### ISSUE THREAD

**Issue by JoernGe** [Gerungofulus/bvd_agent_based_model#4]
In the output tables

> - "BVD_Dead_PIs",
> - "PIs_LIVING_txxx", 
> - "BVD_Dead_Cows" and 
> - "BVD_Cows_Infections"

the name of the last column is wrong. Instead of 

> numberOfVaccinations

 it must be 

> lastVaccinationTimeIndex

**Comment by Yperidis** [comment]
Where do you see the names of the columns for the output tables? In the hdf5 files directly (in that case how do you know that the last column is called "numberOfVaccinations"? It says so in the "OutputTables.xlsx", but I don't see where this is derived from) or in the source code? If in the latter in which file exactly?

**Comment by Gerungofulus** [comment]
The names @JoernGe used where derived from the ```outputSpecification.py```. The definition of what is actually written is located in the TableBasedOutput class, which is extended by the HDF5FileHandler. This class is implementing the actual writing to hdf5 files. If you wanted to implement CSV output, you would write another class doing the same as the HDF5FileHandler, but writing to CSV rather than HDF5

**Comment by Gerungofulus** [comment]
As marked in #7 , I was talking about the [outputSpecification](https://github.com/Gerungofulus/bvd_agent_based_model/blob/develop/pythonScripts/BVDDataAnalyzer/outputSpecification.py).

@JoernGe unfortunately, the table entry specified by you is indeed a counter and not a date (in simulation time). I still need to figure out, why this error occurs.

**Comment by Gerungofulus** [comment]
So this is the code from 

> src/Cow.cpp:534-556


```
inline void Cow::runVaccination(const double& time){
	bool vaccinationWorked = false;
	if( this->infection_status == Infection_Status::SUSCEPTIBLE){
		this->infection_status = Infection_Status::IMMUNE;
		this->herd->remove_cow_from_susceptible( this );

		this->herd->add_r_cow(this);
		vaccinationWorked = true;
//		if(this->herd->farm->next_infection_event != nullptr && this->herd->farm->next_infection_event->id == this->id() && this->herd->farm->next_infection_event->execution_time < time + bvd_const::timeOfVaccinationPersistance)
//			this->herd->farm->invalidate_next_infection_event();
	}
	if(this->end_of_vaccination_event != nullptr){
		system->invalidate_event(this->end_of_vaccination_event);

		this->end_of_vaccination_event = nullptr;
	}
	if(vaccinationWorked){
		this->end_of_vaccination_event = new Event( system->getCurrentTime()+ System::getInstance(nullptr)->activeStrategy->vaccinationTimeOfDefense  , Event_Type::END_OF_VACCINATION      , this->id() );
		system->schedule_event(this->end_of_vaccination_event) ;
	}
	this->scheduleVaccination(time);
	this->numberOfVaccinations++;
}
```

What it should do:
If the cow is immune, it will be moved from the susceptible group to the recovered group (with 100% probability).

If there is a event corresponding to the end of a phase of immunity, for the cow, this event will be invalidated and the cow will forget about it.

If the vaccination worked, which it does with 100% probability, the end of the phase of immunity will be scheduled and the cow will remember it.

The number of vaccinations of that specific cow will be incremented and the vaccination will be scheduled by the following code from the same file:

```
inline void Cow::scheduleVaccination(const double& time){
	double vaccTime = 0.0;
	if(this->age() < bvd_const::firstVaccAge )
		vaccTime = this->birth_time + bvd_const::firstVaccAge + 1;
	else
		vaccTime = time + bvd_const::timeOfVaccinationPersistance;

	system->schedule_event( new Event( vaccTime, Event_Type::VACCINATE, this->id() ) );
}
```

This means the cow is vaccinated for the first time, when it reached the specific age or it will be schedule for right about the time, when the vaccination should wear off.

**Comment by Gerungofulus** [comment]
From
>Cow.cpp: 626-637
```
if(system->activeStrategy->usesVaccination){

		vaccTime = time - System::getInstance(nullptr)->activeStrategy->vaccinationTimeBeforeInsemination;
    std::cout << "before" << std::endl;
    std::cout << vaccTime << "\t" << System::getInstance(nullptr)->getCurrentTime()<< "\t" << vaccTime-c->birth_time << std::endl;
		if(this->end_of_vaccination_event == nullptr || this->end_of_vaccination_event->execution_time > vaccTime){
			vaccTime = (vaccTime-System::getInstance(nullptr)->getCurrentTime()) < bvd_const::firstVaccAge ?  vaccTime : bvd_const::firstVaccAge + System::getInstance(nullptr)->getCurrentTime();
      std::cout << vaccTime << "\t" << System::getInstance(nullptr)->getCurrentTime()<< "\t" << vaccTime-c->birth_time << std::endl;
      system->schedule_event( new Event( vaccTime, Event_Type::VACCINATE, c->id() ) );

		}
	}
```
The output is as follows
```
2446.61	1966.2	480.408
2152.2	1966.2	186
before
2006.34	1968.54	1999.34
2006.34	1968.54	1999.34
before
2475.75	1968.54	507.209
2154.54	1968.54	186
before
2464.25	1972.69	491.565
2158.69	1972.69	186
before
2515.98	1997.27	518.712
2183.27	1997.27	186
```
Meaning that the insemination is scheduled anywhere in the range specified in `Model_Constants.h`, but as the first insemination is scheduled far beyond the first  insemination age of 186.0 days, it will be set down to that mark. The next insemination would take place around the same time as the day of the first insemination (a year later), which could explain why there are multiple vaccination events close to each other, leading to a to high count of vaccinations.

**Comment by Gerungofulus** [comment]
I will refactor the vaccination process tonight and see if it helps. Also it's a little unclear to me, why the `BVD_Random_Number_Generator::vaccinationWorks()` function, which indeed exists, is never used.

**Comment by JoernGe** [comment]
Hi @Gerungofulus ,
your answers raised some more questions:
1:
>What it should do:
>If the cow is immune, it will be moved from the susceptible group to the recovered group (with 100% >probability).
>If there is a event corresponding to the end of a phase of immunity, for the cow, this event will be >invalidated and the cow will forget about it.

Does it mean that if a cow has been vaccinated and the vaccination is successful, it is moved from susceptible to recovered group? Is it possible to distinguish between vaccinated and recovered animals?

2:
>If the vaccination worked, which it does with 100% probability, the end of the phase of immunity will >be scheduled and the cow will remember it.

In the iniFile there is an option to change the working probabilitiy `vaccinationWorkingProbability=0.985`
Does your answer mean, that this initial value is not used?

**Comment by Gerungofulus** [comment]
>Also it's a little unclear to me, why the BVD_Random_Number_Generator::vaccinationWorks() function, >which indeed exists, is never used.
It is used by this function, but this function is never called, so for some reason vaccination does only work with 100% probability. It's a mistake I made and I don't know why. I'm sorry.

**Comment by Gerungofulus** [comment]
I seem to have fixed it. I'm not entirely sure, if all results a 100% reasonable, but it looked quite good.
