### ISSUE TITLE
Influence vaccination (vaccineworkingprobability) on outcome

### ISSUE THREAD

**Issue by JoernGe** [Gerungofulus/bvd_agent_based_model#9]
I tested the model with different settings for the vaccineworkingprobability (VWP) and get some strange results:

- with a high VWP, the PI prevalence without control strategy is higher, than with a low VWP (see plot)
- with high VWP the prevalence increases rapidly after EarTag testing is stopped

![image](https://user-images.githubusercontent.com/29978194/28467065-e77b083c-6e2e-11e7-9b7b-52c949209c31.png)

The simulation starts without control, at t=10000 EarTag testing is implemented.

```
[containment]
strategies=strategy1,strategy2,strategy3,strategy8

[strategy1]
#The values given in this strategy are also the default values for any strategy.
#This means if you don't set them to another value, they will always be set in this way.
#The default values can not be overriden using the ini file.
name=noMeasures
usesEartag=false
usesVaccination=false
usesJungtierFenster=false
startTime=0
bloodTestAccuracy=0.998
retestingTimeBlood=60
vaccinationWorkingProbability=0.8 #default=0.985
vaccinationTimeBeforeInsemination=42
quarantineTime=40
applyQuarantineOnBuying=false
respectQuarantine=true
quarantineAfterPositiveTest=true
jungtierzeit=186
vaccinationTimeOfDefense=365

[strategy8]
usesEartag=false
retestingTimeBlood=40
usesJungtierFenster=false
vaccinationWorkingProbability=0.8 #default=0.985
usesVaccination=true
```
I checked the number of vaccinations for scenario11 (Table: BVD_Cows_Infections) and there are only few vaccinations listed:

year|number of not vaccinated animals|number of vaccinated animals|total number of animals
-- | -- | -- | --
2011 | 81409 |   | 81409
2012 | 65232 |   | 65232
2013 | 58933 |   | 58933
2014 | 55484 |   | 55484
2015 | 50429 |   | 50429
2016 | 45730 |   | 45730
2017 | 39423 |   | 39423
2018 | 81137 | 129 | 81266
2019 | 80563 | 219 | 80782
2020 | 63194 | 114 | 63308
2021 | 58712 | 91 | 58803
2022 | 61391 | 108 | 61499

Looking at the same table for scenario11vwp08, I will have as an result only vaccination before the control program starts: 

year|number of not vaccinated animals|number of vaccinated animals|total number of animals
-- | -- | -- | --
2009 | 67231 | 1449 | 68680
2010 | 66167 | 1410 | 67577
2011 | 60948 | 850 | 61798
2012 | 46214 | 103 | 46317
2013 | 43196 | 70 | 43266
2014 | 45227 | 64 | 45291
2015 | 44941 | 34 | 44975
2016 | 42180 | 15 | 42195
2017 | 38776 | 1 | 38777
2018 | 38235 |   | 38235
2019 | 39239 |   | 39239
2020 | 40522 |   | 40522
2021 | 41772 |   | 41772
2022 | 40866 |   | 40866
2023 | 38877 |   | 38877
2024 | 38368 |   | 38368

In Scenario11VWP09 and Scenario11VWP095 only animals before implementing the control strategies are tested, with  lower numbers than for VWP08 (~1/2 or ~1/4 of vwp08)

**Comment by Gerungofulus** [comment]
Note that strategy2 and strategy3 also need to have a VWP, as it will be reset to 0,98 otherwise. I admit that it's a shame in terms of usability, but I guess it's a start....

I agree that the numbers of vaccinations are strange, I'll investigate it, but I would understand your diagram like everything was perfectly normal. Could you explain it to me?

**Comment by JoernGe** [comment]
Its strange that

1. The prevalence is lower in the scnarios with vaccineworking probability of 0.8, 0.9 and 0.95 before any control strategy started 
2. The number of vaccinations is very low (2,155 %)
3. the vaccination in 
    - scenario11vwp08, 
    - scenario11vwp09, 
    - scenario11vwp095 
starts before the vaccination strategy is started.

When talking about vaccination of pregnant heifers and cows, I would expect that the probability of giving birth to a PI animal is very low:

- the probability of a susceptible animal getting infected is about 20%. 
- the vaccine working probability is 98.5% and 
- the proportion of transiently infected animals is about 5 %, 

I expect a very low number of PI animals per year (0.2*(1-0.985)*0.05=0.00015). As these animals will be undetected (no ear Tag testing), the number of PIs might be increased in the following years.

**Update:** We run the simulation for vaccineworkingprobability=1 and repeated the base scenario (WVP=0.985, adding the vaccinationWorkingProbability=0.985) to all the used strategies.

![image](https://user-images.githubusercontent.com/29978194/28522974-9fff6180-707a-11e7-8a07-e5b2890452ba.png)

**Comment by Gerungofulus** [comment]
@JoernGe Regarding the issue of vaccinations running till the containment strategy should be put into place: you forgot to set 'startTime=0' in strategy 8, so it will be sorted to the 2nd position in the list of containment strategies. The first strategy (strategy1 should be skipped entirely) and therefore vaccinations will be run right from the beginning.

Furthermore only inseminated cows will be vaccinated, so the number of vaccinations in a given time frame is relative to the inseminations in the same timeframe and does not include bulls. Also the working probability will have no effect on the number of vaccinations as every try of a vaccination is counted, not it's success. I thought this would make more sense as it's the try of vaccinating a cow which costs money.

Please give a detailed description of the process if you want any changes. I'm happy to hear your comments.

**Comment by JoernGe** [comment]
@Gerungofulus I checked the ini files several times and didn't see the error, I'm sorry
We will rerun the scenarios, analyse it and check again the results.

The process you describe is in the way, we discussed it before. I will check if the number of vaccinated animals is what we expect in theory:
- each female cattle with at a certain age will be vaccinated about once a year, depending on the between calving time (~ 390-400 days). 
- the vaccination will protect an animal only one year
- from experience, about 1/3 of the cattle population are cows. 

Hence I expected that about 25-33 % of the population is vaccinated each year (0.33*365/390). 
In contrast in the model only 2% of the population are vaccinated each year. 
- Will the vaccine in the model lead to a life long protection?

**Comment by Gerungofulus** [comment]
No the vaccine works for a year and the next vaccination will be scheduled after one year exactly. I understand your concerns. I will look into it

**Comment by Gerungofulus** [comment]
Should I throw an error if two strategies have a to close startTime?

**Comment by JoernGe** [comment]
I don't think that its necessary to throw an error.
Next time I check the *.ini files carefully.
